export const GuamAverage = {
	"Fire_Stations":	4,
	"Flood_Final":	4,
	"Hospitals":	1,
	"Main_Road_Points":	4,
	"Parks":	1,
	"Slope_sample":	5,
	"Schools":	1,
	"Distance_Residential":	4,
	"Distance_transport":	4,
	"HH_halfhour":	4,
	"Distance_Commercial":	4,
	"Distance_Ports":	4
}
export const suitabilityGoals =[{label: 'What are your goals?' , options:[
	{label:'Residential areas', value:'Residential',criteria_factors: [
		{label:'Residential areas should be safe from frequent floods, important for years to coe', value:'Flood Risk',key:'Flood_Final' ,priority: 1,meaning:{
			'1':'AE',
			'2':'A',
			'3':'AH',
			'4':'X',
			'5':'0.2 PERCENT FLOOD ZONE ',
		}},
		{label:'How accessible are main roads from the property, so that emergency services reach faster', value:'Distance from Main Road',key:'Main_Road_Points' ,priority: 1,meaning:{
			'1':'> 1 mile',
			'2':'0.75 - 1 mile',
			'3':'0.5-0.75 mile',
			'4':'0.25-0.5 mile',
			'5':'<0.25 mile',
		}},
		{label: 'Fire safety', value:'Distance from fire station',key:'Fire_Stations' ,priority: 1,meaning:{
			'1':'> 4 miles',
			'2':'3- 4 miles',
			'3':'2- 3 miles',
			'4':'1 - 2 miles',
			'5':'< 1 mile',
		}},
		{label: 'Emergency/Primary medical services', value:'Distance from medicos / hospital',key:'Hospitals' ,priority: 1,
		meaning:{
			'1':'> 4 miles',
			'2':'3- 4 miles',
			'3':'2- 3 miles',
			'4':'1 - 2 miles',
			'5':'< 1 mile',
		}},
		{label: 'Places for recreation, relaxation, exercise within reach', value:'Distance from neighborhood park',key:'Parks' ,priority: 1,meaning:{
			'1':'> 1 mile',
			'2':'0.75 - 1 mile',
			'3':'0.5-0.75 mile',
			'4':'0.25-0.5 mile',
			'5':'<0.25 mile',
		}},
		{label: 'Elementary schools within walking distances from homes', value:'Distance from elementary school',key:'Schools' ,priority: 1,meaning:{
			'1':'> 1 mile',
			'2':'0.75 - 1 mile',
			'3':'0.5-0.75 mile',
			'4':'0.25-0.5 mile',
			'5':'<0.25 mile',
		}},
		{label: 'Flat areas, more safer for home building than those on hills, more prone to widfires, landslides', value:'Slope',key:'Slope_sample' ,priority: 1,meaning:{
			'1':'> 25 degrees',
			'2':'20 - 25 degrees',
			'3':'15 -20 degrees',
			'4':'10 - 15 degrees',
			'5':'<10 degrees',
		}},
	]},
	{label:'Commercial areas', value:'Commercial',criteria_factors: [
		{label:'Commercial areas located close to residential areas get a market. Reduces driving distances and keeps areas lively for most hours a day', value:'Distance from Residential areas',key: 'Distance_Residential' ,priority: 1,meaning:{
			'1':'> 1 mile',
			'2':'0.75 - 1 mile',
			'3':'0.5-0.75 mile',
			'4':'0.25-0.5 mile',
			'5':'<0.25 mile',
		}},
		{label: 'Distance from Public Transport Stations', value:'Distance from Public Transport Stations',key:'Distance_transport' ,priority: 1,meaning:{
			'1':'> 1 mile',
			'2':'0.75 - 1 mile',
			'3':'0.5-0.75 mile',
			'4':'0.25-0.5 mile',
			'5':'<0.25 mile',
		}},
		{label:'Percentage of HHs within half hour driving distance', value:'Percentage of HHs within half hour driving distance',key:'HH_halfhour' ,priority: 1,meaning:{
			'1':'0th to 20 percentile',
			'2':'20th to 40 percentile',
			'3':'40th to 60 percentile',
			'4':'60th to 80 percentile',
			'5':'80th to 100 percentile',
		}},
		{label: 'Distance from Main Roads', value:'Distance from Main Roads',key:'Main_Road_Points' ,priority: 1,meaning:{
			'1':'> 1 mile',
			'2':'0.75 - 1 mile',
			'3':'0.5-0.75 mile',
			'4':'0.25-0.5 mile',
			'5':'<0.25 mile',
		}},
	]},
	{label:'Industrial areas', value:'Industrial',criteria_factors: [
		{label:'Distance from conservation areas', value:'Distance from conservation areas' ,priority: 1,key: 'Distance_Commercial',meaning:{
			'1':'< 1 mile',
			'2':'1 - 2 miles',
			'3':'2- 3 miles',
			'4':'3- 4 miles',
			'5':'> 4 miles',
		}},
		{label:'Distance from Airports/Sea Port', value:'Distance from Airports/Sea Port' ,priority: 1,key: 'Distance_Ports',meaning:{
			'1':'> 4 miles',
			'2':'3- 4 miles',
			'3':'2- 3 miles',
			'4':'1 - 2 miles',
			'5':'< 1 mile',
		}},
		{label: 'Distance from Residential areas', value:'Distance from Residential areas' ,priority: 1,key: 'Distance_Residential',meaning:{
			'1':'<0.25 mile',
			'2':'0.25-0.5 mile',
			'3':'0.5-0.75 mile',
			'4':'10 - 15 degrees',
			'5':'0.75 - 1 mile',
		}},
	]},
]
}]